storage: ./storage
store: 
  # only used for testing, replace with s3 config for production
  # memory:
  #  limit: 1000
  aws-s3-storage:
    bucket: AWS_FILES_BUCKET
    accessKeyId: AWS_ACCESS_KEY_ID
    secretAccessKey: AWS_SECRET_ACCESS_KEY
    region: AWS_REGION
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
    algorithm: bcrypt
    rounds: 10
web:
  title: Verdaccio NPM registry
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    # In case I want to save storage space in AWS, I should disable cache https://verdaccio.org/docs/uplinks/
    # cache: false
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    proxy: npmjs
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated